### ISSUE TITLE
圆角V2在2.3.3版本中无效

### ISSUE THREAD

**Issue by lh4111** [zhitaocai/CocosCreatorShaderEffectDemo#2]
圆角V2在cocos creator 2.3.3版本中在web浏览器上无效，编辑器中可以看到效果

**Comment by zhitaocai** [comment]
## 解决方案

1. 使用我的demo在2.3.3去跑一下，而不是你的demo，检查我的demo是否运行正确
2. 如果我的demo正确，那么大概率是你使用时忽略一些点，比如：
    * 使用圆角的纹理，被动态合图了
        * 一些解决方案（选其中一个合适自己的）：
            * 关闭动态合图。如在 `onLoad` 中调用： `cc.dynamicAtlasManager.enabled = false;`
            * 使用圆角的纹理，不要打包进动态合图中，在编辑器选中你的纹理，不要勾选 Packable

![image](https://user-images.githubusercontent.com/5856724/81469168-1fe10d80-9216-11ea-83d7-1d849eb0ed3d.png)

**Comment by zhitaocai** [comment]
> 圆角V2在cocos creator 2.3.3版本中在web浏览器上无效，编辑器中可以看到效果

# 任何在编辑器表现正常，在浏览器表现不正常的问题，请参考以下解决方案

## 解决方案

1. 使用我的demo在2.3.3去跑一下，而不是你的demo，检查我的demo是否运行正确
2. 如果我的demo正确，那么大概率是你使用时忽略一些点，比如：
    * 使用「圆角特效」的纹理，被动态合图了
        * 一些解决方案（选其中一个合适自己的）：
            * 关闭动态合图。如在 `onLoad` 中调用： `cc.dynamicAtlasManager.enabled = false;`
            * 使用圆角的纹理，不要打包进动态合图中，在编辑器选中你的纹理，不要勾选 Packable

![image](https://user-images.githubusercontent.com/5856724/81469168-1fe10d80-9216-11ea-83d7-1d849eb0ed3d.png)
