### ISSUE TITLE
内发光在模拟器不见了

### ISSUE THREAD

**Issue by bytetalking** [zhitaocai/CocosCreatorShaderEffectDemo#3]
内发光在模拟器， 图片直接不见了， 光也没有

**Comment by zhitaocai** [comment]
浏览器正常吗，编辑器正常吗

**Comment by zhitaocai** [comment]
> 内发光在模拟器， 图片直接不见了， 光也没有

浏览器正常吗，编辑器正常吗

**Comment by bytetalking** [comment]
对，浏览器正常， 编辑器也正常， packable是没勾的，cocos creator版本2.3.4, 自己参考实现的有这个问题， 后来下载你写的， 也一样

**Comment by zhitaocai** [comment]
我用我这个项目的内发光Demo场景，直接模拟器运行时可以的
![image](https://user-images.githubusercontent.com/5856724/83411306-90143500-a44a-11ea-9d21-ab015199cd46.png)

**Comment by bytetalking** [comment]
这就奇怪了， 我下载你完整项目打开是没问题的， 单独拷贝这个shader的代码去我的项目使用， 是有问题，不知道啥原因～

**Comment by bytetalking** [comment]
找到原因了， for循环的问题
